import type { CaseRecord } from "./types";

const evidencePool = [
  { id: "ev-01", name: "Fence Damage.jpg", type: "image" as const, url: "https://images.unsplash.com/photo-1523419400524-fc1e0a31b6ce?w=1200", thumbnail: "https://images.unsplash.com/photo-1523419400524-fc1e0a31b6ce?w=200", size: "2.4 MB", uploadedAt: "02/23/2026" },
  { id: "ev-02", name: "Threat Messages.jpg", type: "image" as const, url: "https://images.unsplash.com/photo-1510146758428-e5e4b17b8b6e?w=1200", thumbnail: "https://images.unsplash.com/photo-1510146758428-e5e4b17b8b6e?w=200", size: "1.1 MB", uploadedAt: "02/23/2026" },
  { id: "ev-03", name: "Disturbance Night.jpg", type: "image" as const, url: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1200", thumbnail: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=200", size: "3.2 MB", uploadedAt: "02/22/2026" },
  { id: "ev-04", name: "Damaged Gate.jpg", type: "image" as const, url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200", thumbnail: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=200", size: "2.8 MB", uploadedAt: "02/21/2026" },
  { id: "ev-05", name: "Incident Report.pdf", type: "document" as const, url: "https://images.unsplash.com/photo-1454165205744-3b78555e5572?w=1200", thumbnail: "https://images.unsplash.com/photo-1454165205744-3b78555e5572?w=200", size: "1.5 MB", uploadedAt: "02/20/2026" },
  { id: "ev-06", name: "Witness Statement.pdf", type: "document" as const, url: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1200", thumbnail: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=200", size: "340 KB", uploadedAt: "02/23/2026" },
  { id: "ev-07", name: "CCTV Capture.jpg", type: "image" as const, url: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=1200", thumbnail: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=200", size: "4.1 MB", uploadedAt: "02/19/2026" },
];

export const mockCases: CaseRecord[] = [
  {
    id: "1",
    caseNumber: "IRIS-2026-001",
    fullName: "Roselyn Lei B. Ong",
    shortName: "R. Ong",
    category: "Violence or Threats",
    type: "Threat",
    priority: "High",
    status: "Mediation",
    assignedOfficer: "R. Augustine",
    date: "02/23/2026",
    gender: "Female",
    contact: "09000000000",
    email: "roselynong0@gmail.com",
    street: "09000000000 Star, Street, De Guzman",
    details: "There was a comment from my neighbor threatening me to be beat up if he said he saw me.",
    dateSubmitted: "02/23/2026",
    incidentDate: "02/23/2026",
    evidence: 4,
    evidenceFiles: [evidencePool[1], evidencePool[0], evidencePool[4], evidencePool[5]],
  },
  {
    id: "2",
    caseNumber: "IRIS-2026-002",
    fullName: "Ricardo M. Tolentino",
    shortName: "R. Tolentino",
    category: "Harassment & Abuse",
    type: "Bullying",
    priority: "Medium",
    status: "Pending",
    assignedOfficer: "R. Augustine",
    date: "02/23/2026",
    gender: "Male",
    contact: "09171234567",
    email: "rtolentino@yahoo.com",
    street: "45 Sampaguita St., Brgy. San Jose",
    details: "My son has been experiencing repeated bullying from a group of teenagers in our barangay, including verbal abuse and intimidation after school hours.",
    dateSubmitted: "02/23/2026",
    incidentDate: "02/20/2026",
    evidence: 2,
    evidenceFiles: [evidencePool[1], evidencePool[5]],
  },
  {
    id: "3",
    caseNumber: "IRIS-2026-003",
    fullName: "Roberto J. Augustine",
    shortName: "R. Augustine",
    category: "Fraud & Scams",
    type: "Online Scam",
    priority: "Medium",
    status: "Under Review",
    assignedOfficer: "M. Santos",
    date: "02/23/2026",
    gender: "Male",
    contact: "09281234567",
    email: "raugustine@gmail.com",
    street: "12 Mabini Ave., Poblacion",
    details: "I was scammed online through a fake marketplace listing. I transferred P15,000 for electronics that were never delivered. The seller has since blocked all communication.",
    dateSubmitted: "02/23/2026",
    incidentDate: "02/18/2026",
    evidence: 6,
    evidenceFiles: [evidencePool[1], evidencePool[6], evidencePool[4], evidencePool[5], evidencePool[0], evidencePool[2]],
  },
  {
    id: "4",
    caseNumber: "IRIS-2026-004",
    fullName: "Maria C. Augustine",
    shortName: "M. Augustine",
    category: "Public Disturbance",
    type: "Noise Complaint",
    priority: "High",
    status: "Resolved",
    assignedOfficer: "R. Augustine",
    date: "02/23/2026",
    gender: "Female",
    contact: "09351234567",
    email: "maugustine@outlook.com",
    street: "78 Rizal St., Brgy. Centro",
    details: "There has been continuous loud karaoke music from a neighbor every night past midnight for the last two weeks, causing sleep disturbance for multiple families.",
    dateSubmitted: "02/23/2026",
    incidentDate: "02/15/2026",
    evidence: 1,
    evidenceFiles: [evidencePool[2]],
  },
  {
    id: "5",
    caseNumber: "IRIS-2026-005",
    fullName: "Ramon P. Dela Cruz",
    shortName: "R. Dela Cruz",
    category: "Property & Theft",
    type: "Property Damage",
    priority: "High",
    status: "Pending",
    assignedOfficer: "M. Santos",
    date: "02/23/2026",
    gender: "Male",
    contact: "09451234567",
    email: "rdelacruz@gmail.com",
    street: "33 Luna St., Brgy. Bagumbayan",
    details: "My fence and front gate were deliberately damaged during an altercation with a neighbor over a land boundary dispute. There is also evidence of stolen construction materials.",
    dateSubmitted: "02/23/2026",
    incidentDate: "02/21/2026",
    evidence: 5,
    evidenceFiles: [evidencePool[0], evidencePool[3], evidencePool[6], evidencePool[4], evidencePool[5]],
  },
  {
    id: "6",
    caseNumber: "IRIS-2026-006",
    fullName: "Elena S. Villanueva",
    shortName: "E. Villanueva",
    category: "Community Dispute",
    type: "Boundary Dispute",
    priority: "Medium",
    status: "Mediation",
    assignedOfficer: "R. Augustine",
    date: "02/22/2026",
    gender: "Female",
    contact: "09561234567",
    email: "evillanueva@gmail.com",
    street: "56 Bonifacio St., Brgy. Maligaya",
    details: "An ongoing boundary dispute with my adjacent neighbor who has been encroaching on my property by extending their fence line. This has been ongoing for 3 months.",
    dateSubmitted: "02/22/2026",
    incidentDate: "02/10/2026",
    evidence: 3,
    evidenceFiles: [evidencePool[0], evidencePool[4], evidencePool[5]],
  },
  {
    id: "7",
    caseNumber: "IRIS-2026-007",
    fullName: "Patricia Ann G. Reyes",
    shortName: "P. Reyes",
    category: "Child & Vulnerable Protection",
    type: "Child Neglect",
    priority: "High",
    status: "Under Review",
    assignedOfficer: "M. Santos",
    date: "02/22/2026",
    gender: "Female",
    contact: "09671234567",
    email: "preyes@gmail.com",
    street: "89 Aguinaldo St., Brgy. Pag-asa",
    details: "Reporting concern for children in a neighboring household who appear to be left unsupervised for extended periods.",
    dateSubmitted: "02/22/2026",
    incidentDate: "02/19/2026",
    evidence: 2,
    evidenceFiles: [evidencePool[2], evidencePool[6]],
  },
  {
    id: "8",
    caseNumber: "IRIS-2026-008",
    fullName: "Jose L. Manalo",
    shortName: "J. Manalo",
    category: "Violence or Threats",
    type: "Physical Assault",
    priority: "High",
    status: "Closed",
    assignedOfficer: "R. Augustine",
    date: "02/20/2026",
    gender: "Male",
    contact: "09781234567",
    email: "jmanalo@yahoo.com",
    street: "21 Del Pilar St., Brgy. Santo Nino",
    details: "I was physically assaulted by an intoxicated individual outside a local store. I sustained minor injuries and filed this report for documentation and action.",
    dateSubmitted: "02/20/2026",
    incidentDate: "02/20/2026",
    evidence: 3,
    evidenceFiles: [evidencePool[6], evidencePool[4], evidencePool[5]],
  },
  {
    id: "9",
    caseNumber: "IRIS-2026-009",
    fullName: "Anna Marie T. Lim",
    shortName: "A. Lim",
    category: "Harassment & Abuse",
    type: "Verbal Abuse",
    priority: "Medium",
    status: "Pending",
    assignedOfficer: "M. Santos",
    date: "02/21/2026",
    gender: "Female",
    contact: "09891234567",
    email: "alim@gmail.com",
    street: "67 Quezon Ave., Brgy. Kamuning",
    details: "Consistent verbal abuse and threats from a co-worker at our local market stall.",
    dateSubmitted: "02/21/2026",
    incidentDate: "02/21/2026",
    evidence: 1,
    evidenceFiles: [evidencePool[1]],
  },
  {
    id: "10",
    caseNumber: "IRIS-2026-010",
    fullName: "Fernando B. Cruz",
    shortName: "F. Cruz",
    category: "Fraud & Scams",
    type: "Identity Fraud",
    priority: "High",
    status: "Under Review",
    assignedOfficer: "R. Augustine",
    date: "02/19/2026",
    gender: "Male",
    contact: "09901234567",
    email: "fcruz@outlook.com",
    street: "102 Legaspi St., Brgy. Poblacion",
    details: "Someone used my personal information to take out multiple loans from lending apps. I discovered unauthorized accounts and transactions totaling P50,000.",
    dateSubmitted: "02/19/2026",
    incidentDate: "02/17/2026",
    evidence: 7,
    evidenceFiles: [evidencePool[1], evidencePool[6], evidencePool[0], evidencePool[3], evidencePool[4], evidencePool[5], evidencePool[2]],
  },
];
